import random
def Random(x):
    r = random.randint(1, x)
    return r

x = int(input("Choose a number between 1 and infinity: "))
r = Random(x)
print("Guess the number generated by the computer inclusively between 1 and {}: ".format(x))
y = int(input())
while(y!= r):
    if(y>r):
        print(f"...{y} is too large. Guess again!")
        
    elif(y<r):
        print(f"...{y} is too small. Guess again!")

    y = int(input())

print("You are correct!")